## Numpy
## Pandas

## Numpy

- Numerical python ,popularly known as numpy has been designed to carry out mathematical computations at a faster and easier rate
- numpy provides a large library of high level mathematical functions to operate on data structures

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
np.__version__

'1.16.2'

In [5]:
arr = np.array([12,23,34])
arr

array([12, 23, 34])

In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
li = [1,2,3]
li

[1, 2, 3]

In [9]:
type(li)

list

In [12]:
arr1 = np.array([12,3.5,"apssdc"])
type(arr1)

numpy.ndarray

In [13]:
arr1.dtype

dtype('<U32')

In [14]:
arr2 = np.array("24-07-2020")
arr2.dtype

dtype('<U10')

In [15]:
arr3 = np.array(3+4j)
arr3.dtype

dtype('complex128')

In [16]:
range(1,10)

range(1, 10)

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
range(1,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
np.arange(1,10.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.arange(1,10.5,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [29]:
arr4 = np.arange(1,200,2)

In [23]:
arr4

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [25]:
arr4[0],arr4[1]

(1, 3)

In [26]:
arr4[10:50]

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87,
       89, 91, 93, 95, 97, 99])

In [27]:
arr4.shape

(100,)

- 1D array  - point
- 2D array  -square
- 3D array  - cubic

In [30]:
arr4.ndim

1

In [36]:
a = arr4.reshape(10,10)
a

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29,  31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69,  71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149, 151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
       [181, 183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [37]:
a.ndim

2

In [38]:
arr4.reshape(-1,10)

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29,  31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69,  71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149, 151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
       [181, 183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [40]:
arr4.reshape(5,-1)

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,  65,
         67,  69,  71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105,
        107, 109, 111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145,
        147, 149, 151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185,
        187, 189, 191, 193, 195, 197, 199]])

In [41]:
len(arr4)

100

In [42]:
arr4.shape

(100,)

In [43]:
arr4.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [46]:
arr4.reshape(4,-1)

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49],
       [ 51,  53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,
         77,  79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
        127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149],
       [151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175,
        177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [51]:
arr5 = np.arange(0,20).reshape(2,2,5)

In [52]:
arr5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [53]:
arr5.ndim

3

In [54]:
arr5.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [55]:
arr5.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [1]:
li = [2,3,4] #[4,5,6]
l = []
for ele in li:
    l.append(ele+2)
print(l)

[4, 5, 6]


In [3]:
ar = np.array([2,3,4])
ar

array([2, 3, 4])

In [4]:
ar+2

array([4, 5, 6])

In [6]:
ar*5

array([10, 15, 20])

In [7]:
ar-6

array([-4, -3, -2])

In [8]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
ar>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [10]:
ar[ar>5]

array([6, 7, 8, 9])

In [12]:
ar%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

In [13]:
ar[ar%2==0]

array([2, 4, 6, 8])

- np.logical_and()
- np.logical_or()
- np.logical_not()

In [14]:
y = np.arange(1900,2021)
y

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

divisible by 4 and 400
not divisible by 100

In [ ]:
a = np.logical_and(y%4==0,y%400==0)
np.logical_or(y%100!=0,a)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
a = np.zeros((2,10),dtype = object)
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [20]:
a.dtype

dtype('O')

In [22]:
one = np.ones((10,10),dtype = int)
print(one)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [24]:
np.eye(10,20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

- Trignometric methods

In [25]:
np.sin(90)

0.8939966636005579

In [26]:
np.sin(np.deg2rad(90))

1.0

In [27]:
np.sinh(45)

1.7467135528742547e+19

### Statistical methods

In [28]:
ar = np.arange(500)

In [29]:
ar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [30]:
np.min(ar)

0

In [31]:
np.max(ar)

499

In [33]:
np.median(ar)

249.5

In [34]:
np.sum(ar)

124750

In [35]:
np.cumsum(ar)

array([     0,      1,      3,      6,     10,     15,     21,     28,
           36,     45,     55,     66,     78,     91,    105,    120,
          136,    153,    171,    190,    210,    231,    253,    276,
          300,    325,    351,    378,    406,    435,    465,    496,
          528,    561,    595,    630,    666,    703,    741,    780,
          820,    861,    903,    946,    990,   1035,   1081,   1128,
         1176,   1225,   1275,   1326,   1378,   1431,   1485,   1540,
         1596,   1653,   1711,   1770,   1830,   1891,   1953,   2016,
         2080,   2145,   2211,   2278,   2346,   2415,   2485,   2556,
         2628,   2701,   2775,   2850,   2926,   3003,   3081,   3160,
         3240,   3321,   3403,   3486,   3570,   3655,   3741,   3828,
         3916,   4005,   4095,   4186,   4278,   4371,   4465,   4560,
         4656,   4753,   4851,   4950,   5050,   5151,   5253,   5356,
         5460,   5565,   5671,   5778,   5886,   5995,   6105,   6216,
      

In [36]:
np.cumprod(ar)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [39]:
ar1 = np.arange(1,100)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
np.cumprod(ar1)

array([          1,           2,           6,          24,         120,
               720,        5040,       40320,      362880,     3628800,
          39916800,   479001600,  1932053504,  1278945280,  2004310016,
        2004189184,  -288522240,  -898433024,   109641728, -2102132736,
       -1195114496,  -522715136,   862453760,  -775946240,  2076180480,
       -1853882368,  1484783616, -1375731712, -1241513984,  1409286144,
         738197504, -2147483648, -2147483648,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,      

### Random numbers

In [41]:
np.random.randint(1,100)

44

In [42]:
np.random.randint(1,100)

51

In [43]:
np.random.random(10)

array([0.83118817, 0.18950355, 0.40742822, 0.86049958, 0.48931872,
       0.92410979, 0.53829016, 0.42205618, 0.33796427, 0.3575365 ])

In [44]:
np.random.randn(1,10)

array([[-1.15347332, -0.28639384,  1.08840007, -0.67710772, -0.79869705,
        -0.41027609, -0.92533808,  0.84034356,  1.48427322, -1.51412461]])

In [45]:
np.random.random_integers(1,90)

C:\Users\Alekhya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 90 + 1) instead
  """Entry point for launching an IPython kernel.


55

In [46]:
a1 = np.arange(0,9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
a2 = np.arange(9,18).reshape(3,3)

In [48]:
a2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [49]:
a1*a2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [50]:
a1+a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [51]:
a1.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [52]:
a2.T

array([[ 9, 12, 15],
       [10, 13, 16],
       [11, 14, 17]])

In [53]:
np.diagonal(a1)

array([0, 4, 8])

In [54]:
np.diagonal(a2)

array([ 9, 13, 17])

In [55]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [56]:
help(np.diagonal)

Help on function diagonal in module numpy:

diagonal(a, offset=0, axis1=0, axis2=1)
    Return specified diagonals.
    
    If `a` is 2-D, returns the diagonal of `a` with the given offset,
    i.e., the collection of elements of the form ``a[i, i+offset]``.  If
    `a` has more than two dimensions, then the axes specified by `axis1`
    and `axis2` are used to determine the 2-D sub-array whose diagonal is
    returned.  The shape of the resulting array can be determined by
    removing `axis1` and `axis2` and appending an index to the right equal
    to the size of the resulting diagonals.
    
    In versions of NumPy prior to 1.7, this function always returned a new,
    independent array containing a copy of the values in the diagonal.
    
    In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal,
    but depending on this fact is deprecated. Writing to the resulting
    array continues to work as it used to, but a FutureWarning is issued.
    
    Starting in NumPy

## Pandas

- panadas mainly used for data manipulation,data cleaning,data visuvalization

- Data manipulation:
    - it is used for addung,deleting and modifying data in database
- Data cleaning:
    - it is a process of prparing data for analysis by removing or modifying data that is incorrect,incomplete,irrelevant,duplicate or improperly formatted.
- Data Visuvalization:
    - it is used for graphical representation of data

- Panads are having two ways:
    - Series
    - DataFrames

In [57]:
import pandas as pd

In [59]:
ser = pd.Series([10,20,30])
ser

0    10
1    20
2    30
dtype: int64

In [60]:
ser1 = pd.Series([10,20,30.5,"apssdc"])
ser1

0        10
1        20
2      30.5
3    apssdc
dtype: object

In [61]:
ser1[0]

10

In [62]:
ser1[4]

KeyError: 4

In [66]:
ser1 = pd.Series(["alekhya","narmada","phani","subbareddy"],index = ["ece",23,"*","23.5"])
ser1

ece        alekhya
23         narmada
*            phani
23.5    subbareddy
dtype: object

In [67]:
ser1["*"]

'phani'

In [68]:
ser1["ece"][2]

'e'

In [72]:
pd.Series([input(),int(input())],index = [input(),input()])

alekhya
20
ece
1


ece    alekhya
1           20
dtype: object

In [73]:
a = pd.Series({"name":"APSSDC","state":"AP"})
a

name     APSSDC
state        AP
dtype: object

In [74]:
a["name"]

'APSSDC'

In [75]:
a.index

Index(['name', 'state'], dtype='object')

In [76]:
ser1.index

Index(['ece', 23, '*', '23.5'], dtype='object')

In [77]:
a.colums

AttributeError: 'Series' object has no attribute 'colums'

In [3]:
data = pd.DataFrame({"names":["alekhya","narmada","phani"],"branch":["ece","eee","it"],
              "Des":["multi","software","technical"]})
data


names branch        Des
0  alekhya    ece      multi
1  narmada    eee   software
2    phani     it  technical

In [121]:
data1 = pd.Series({"names":["alekhya","narmada","phani"],"branch":["ece","eee","it"],
              "Des":["multi","software","technical"]})
data1

names        [alekhya, narmada, phani]
branch                  [ece, eee, it]
Des       [multi, software, technical]
dtype: object

In [80]:
data.index

RangeIndex(start=0, stop=3, step=1)

In [83]:
data.columns

Index(['names', 'branch', 'Des'], dtype='object')

In [84]:
data

names branch        Des
0  alekhya    ece      multi
1  narmada    eee   software
2    phani     it  technical

In [89]:
data.describe

<bound method NDFrame.describe of      names branch        Des
0  alekhya    ece      multi
1  narmada    eee   software
2    phani     it  technical>

In [90]:
data.describe()

names branch       Des
count       3      3         3
unique      3      3         3
top     phani    ece  software
freq        1      1         1

In [87]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
names     3 non-null object
branch    3 non-null object
Des       3 non-null object
dtypes: object(3)
memory usage: 152.0+ bytes


In [88]:
data.values

array([['alekhya', 'ece', 'multi'],
       ['narmada', 'eee', 'software'],
       ['phani', 'it', 'technical']], dtype=object)

In [91]:
data

names branch        Des
0  alekhya    ece      multi
1  narmada    eee   software
2    phani     it  technical

In [92]:
data["names"]

0    alekhya
1    narmada
2      phani
Name: names, dtype: object

In [93]:
data["names"][1]

'narmada'

In [96]:
data["branch"][2]

'it'

In [97]:
data["branch"][2][0]

'i'

In [107]:
a = data[["names","branch"]]
a

names branch
0  alekhya    ece
1  narmada    eee
2    phani     it

In [108]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
names     3 non-null object
branch    3 non-null object
dtypes: object(2)
memory usage: 128.0+ bytes


In [109]:
a.describe()

names branch
count       3      3
unique      3      3
top     phani    ece
freq        1      1

In [110]:
a.index

RangeIndex(start=0, stop=3, step=1)

In [111]:
a.columns

Index(['names', 'branch'], dtype='object')

In [114]:
data[["names","Des"]]

names        Des
0  alekhya      multi
1  narmada   software
2    phani  technical

In [115]:
data[["names","Des"]].columns

Index(['names', 'Des'], dtype='object')